# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b00e13a428d8b049f2fed77a109307219847fb9357f8dc3669c98724493e05197166881c1ef04daf78080641ca2f8d77d509c185dca5e19ce9eaf3a0b7930199

test:
  secret_key_base: 6c305133e80a127578052fd8024da24db462e2030560284bf47436980cfcf7c87a587778f3b52c47dbe2ab9047f7184794ec82cae6c34b3a32e13b2b96dcb624

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
